/*
  # Add Storage Policies for lead-magnet Bucket

  1. Summary
    Adds RLS access policies to the `lead-magnet` storage bucket so that:
    - The service role can read files (used by the edge function to generate signed URLs)
    - Authenticated users (Supabase dashboard admins) can read and manage files

  2. Policies Added
    - "Service role can read lead-magnet objects": allows service_role to SELECT from storage.objects
    - "Authenticated users can read lead-magnet objects": allows authenticated users to SELECT (enables dashboard browsing)
    - "Authenticated users can insert lead-magnet objects": allows uploading files via the dashboard
    - "Authenticated users can delete lead-magnet objects": allows managing files via the dashboard

  3. Notes
    - The bucket remains private (not public) — direct URL access is still blocked
    - Signed URLs generated by the edge function are still the intended access path for end users
    - These policies only unlock server-side and dashboard access
*/

CREATE POLICY "Service role can read lead-magnet objects"
  ON storage.objects FOR SELECT
  TO service_role
  USING (bucket_id = 'lead-magnet');

CREATE POLICY "Authenticated users can read lead-magnet objects"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'lead-magnet');

CREATE POLICY "Authenticated users can insert lead-magnet objects"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'lead-magnet');

CREATE POLICY "Authenticated users can delete lead-magnet objects"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'lead-magnet');
